src/Entity/Films.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmsRepository::class)]
class Films
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 30)]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $score;

    #[ORM\Column(type: 'integer')]
    private $VotersNumber;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getVotersNumber(): ?int
    {
        return $this->VotersNumber;
    }

    public function setVotersNumber(int $VotersNumber): self
    {
        $this->VotersNumber = $VotersNumber;

        return $this;
    }
}

src/Form/FileUploadType.php
<?php
// src/Form/FileUploadType.php
namespace App\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class FileUploadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('upload_file', FileType::class, [
                'label' => 'Fichier : ',
                'mapped' => false, // Tell that there is no Entity to link
                'required' => true,
                'constraints' => [
                    new File([
                        'mimeTypes' => [ // We want to let upload only txt, csv or Excel files
                            'text/csv'
                        ],
                        'mimeTypesMessage' => "Document non valide.",
                    ])
                ],
            ])
            ->add('send', SubmitType::class); // We could have added it in the view, as stated in the framework recommendations
    }
}

src/Form/FilmsType.php
<?php

namespace App\Form;

use App\Entity\Films;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            # ->add('description')
            ->add('score')
            ->add('e-mail', EmailType::class, ['mapped'=>false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Films::class,
        ]);
    }
}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use App\Form\FileUploadType;
use App\Form\FilmsType;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Films;
use aharen\OMDbAPI;
use League\Csv\Reader;


class FilmsController extends AbstractController{

    // add film to DB
    public function createFilms(Request $request, EntityManagerInterface $entityManager): ?Response{
        $film = new Films();
        $form = $this->createForm(FilmsType::class, $film);
        $apiKey = '121c13b3'; // clé API

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $url = "http://www.omdbapi.com/?apikey=" . $apiKey . "&t=" . $film->getName();
            $response = file_get_contents($url);
            if(!isset(json_decode($response,true)["Plot"])){ // verify if the film exists
                return new Response("Le film que vous avez essayé d'ajouter n'existe pas.");
            }else{
                $plot = json_decode($response,true)["Plot"];
                $film->setDescription($plot);
                $film->setVotersNumber(1);
                $entityManager->persist($film);
                $entityManager->flush();
            }
        }
        return $this->render('ajoutFilm.html.twig', [
            'form' => $form->createView()
        ]);
    }

    // display films
    public function printFilms(Request $request, ManagerRegistry $doctrine)
    {
        $entityManager = $doctrine->getManager();

        $films = $entityManager->getRepository(Films::class)->findBy([], ['score' => 'desc', 'name' => 'asc']);

        return $this->render('listeFilms.html.twig', [
                'films' => $films
        ]);
    }

    // detail page for each film
    public function detailsFilm(ManagerRegistry $doctrine,$id,Request $request){
        $entityManager = $doctrine->getManager();
        $film = $entityManager->getRepository(Films::class)->find($id);

        $form = $this->createFormBuilder()
            ->add('password', TextType::class)
            ->add('submitForm', SubmitType::class, ['label'=>'delete film '])
            ->getForm()
        ;

        $form ->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $data=$form->getData();
            if($data['password']==$this->getParameter('app.pwd')) // get the admin pwd from parameters
            {
                $entityManager->remove($film);
                $entityManager ->flush();
                return $this->redirectToRoute('listeFilm');
            }
        }
        return $this->render('detail.html.twig', ['film' => $film, 'deleteFilm' => $form->createView()]);

    }

    // upload CSV file
    public function uploadFilms(EntityManagerInterface $entityManager,Request $request, FileUploader $fileUploader){

        $form = $this->createForm(FileUploadType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $file = $form['upload_file']->getData();
            if ($file)
            {
                $file_name = $fileUploader->upload($file);
                if (null !== $file_name) // for example
                {
                    $directory = $fileUploader->getTargetDirectory();
                    $full_path = $directory.'/'.$file_name;
                    $csv = Reader::createFromPath($full_path)
                        ->setHeaderOffset(0); // set the header at the beginning of the file
                    foreach($csv as $record){
                        $film = new Films();
                        $film->setName($record['name']);
                        $film->setDescription($record['description']);
                        $film->setScore((int)$record['score']);
                        $film->setVotersNumber($record['voters']);
                        $entityManager->persist($film);
                        $entityManager->flush();
                    }
                }
                else
                {
                    return new Response('Erreur lors de la lecture du fichier.');
                }
            }
        }
        return $this->render('uploadFilms.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/ajoutFilm.html.twig
{% include 'header.html' %}
{% block body %}
    <h1>Ajouter un film à la base de données :</h1>
    {{ form_start(form) }}
    {{ form_label(form.name) }}
    {{ form_widget(form.name) }}

    {#
    {{ form_label(form.description) }}
    {{ form_widget(form.description) }}  #}

    {{ form_label(form.score) }}
    {{ form_widget(form.score) }}

    {{ form_rest(form) }}

    <button type="submit">Enregistrer</button>
    {{ form_end(form) }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/detail.html.twig
{% include 'header.html' %}
<!DOCTYPE html>
<html>
<body>
<div class="nav-bg">
{{ form_start(deleteFilm) }}
<div>{{form_row(deleteFilm.password)}}</div>
<div>{{form_row(deleteFilm.submitForm)}}</div>
{{ form_end(deleteFilm) }}
</div>
<div class="detail">
<h1>{{ film.getName() }}</h1>
<p>Note : </p>{{ film.getScore() }}
<p>Description : </p>{{ film.getDescription() }}
</div>
</body>
</html>

templates/listeFilms.html.twig
{% include 'header.html' %}

{% block body %}
    <h2>Liste des films :</h2>
    {% for film in films %}
        <h3><a href="{{ path('detailsFilm', { 'id': film.id }) }}">{{ film.name}}</a></h3>
        <div>Description : {{ film.description }}</div>
        <div>Score : {{ film.score }}</div>
        <div>Nombre de votants : {{ film.votersNumber }}</div>
    {% endfor %}

{% endblock %}

templates/uploadFilms.html.twig
{% include 'header.html' %}
{% block content %}
    <h1>Déposer un fichier CSV :</h1>
    <div class="container container-fluid">
        <div class="row">
            <div class="col-lg-8">
                {{ form_start(form, { attr: { 'accept-charset' : 'utf-8' }}) }}
                <div class="form-group">
                    {{ form_label(form.upload_file) }}
                    {{ form_widget(form.upload_file) }}
                    {{ form_errors(form.upload_file) }}
                </div>
                <div class="form-group">
                    {{ form_widget(form.send, {'label': "Upload", 'attr' : { 'class': 'btn btn-primary' }}) }}
                </div>
                {{ form_rest(form) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}